insert into User (id,name, school) values(1 ,Shelton, Omaha Benson High school Magnet)
insert into User (id,name, school) values(2 ,Ed, Millard South High School)
insert into User (id,name, school) values(3 ,Jacky, Parrish)
insert into User (id,name, school) values(4 ,Alease, OPS Career Center)
insert into User (id,name, school) values(5 ,Cummings, Blackburn B)
insert into User (id,name, school) values(6 ,Rosemarie, Blackburn High)
insert into User (id,name, school) values(7 ,Rory, Yates)
insert into User (id,name, school) values(8 ,Latashia, Westside high school)
insert into User (id,name, school) values(9 ,Lucio, Omaha Burke High School)
insert into User (id,name, school) values(10 ,Stacy, Blackburn High)
insert into User (id,name, school) values(11 ,Jack, Blackburn B)
insert into User (id,name, school) values(12 ,Race, Omaha Northwest High school)
insert into User (id,name, school) values(13 ,Joy, Millard West High School)
insert into User (id,name, school) values(14 ,Bobbie, Millard West High School)
insert into User (id,name, school) values(15 ,Georgie, Hogwarts)
insert into User (id,name, school) values(16 ,Harry, Blackburn High)
insert into User (id,name, school) values(17 ,Ed, Millard Horizon High School)
insert into User (id,name, school) values(18 ,Cummings, Parrish)
insert into User (id,name, school) values(19 ,Cummings, Wilson)
insert into User (id,name, school) values(20 ,Guill, Hogwarts)
insert into User (id,name, school) values(21 ,Theo, Hogwarts)
insert into User (id,name, school) values(22 ,Perrier, Millard South High School)
insert into User (id,name, school) values(23 ,Federico, Millard West High School)
insert into User (id,name, school) values(24 ,Jon, Millard West High School)
insert into User (id,name, school) values(25 ,Jon, Millard West High School)
insert into User (id,name, school) values(26 ,Zelda, Omaha Northwest High school)
insert into User (id,name, school) values(27 ,Jack, Brooke Valley School)
insert into User (id,name, school) values(28 ,Zelda, Brooke Valley School)
insert into User (id,name, school) values(29 ,Bobbie, OPS Career Center)
insert into User (id,name, school) values(30 ,Latashia, Omaha North High School)
insert into User (id,name, school) values(31 ,Barry, Omaha South High School)
insert into User (id,name, school) values(32 ,Barry, Wilson)
insert into User (id,name, school) values(33 ,Latashia, Wilson)
insert into User (id,name, school) values(34 ,Neriohord, Blackburn High)
insert into User (id,name, school) values(35 ,Regine, Omaha Northwest High school)
insert into User (id,name, school) values(36 ,Robt, Elkhon South High)
insert into User (id,name, school) values(37 ,Oralia, Omaha Burke High School)
insert into User (id,name, school) values(38 ,Latia, Omaha Benson High school Magnet)
insert into User (id,name, school) values(39 ,Scot, Millard North High School)
insert into User (id,name, school) values(40 ,Marlana, Yates)
insert into User (id,name, school) values(41 ,Neufeld, Omaha North High School)
insert into User (id,name, school) values(42 ,Jacky, Omaha Benson High school Magnet)
insert into User (id,name, school) values(43 ,Regine, Wilson)
insert into User (id,name, school) values(44 ,Gino, Millard South High School)
insert into User (id,name, school) values(45 ,Latia, Omaha Northwest High school)
insert into User (id,name, school) values(46 ,Bobbie, Omaha Northwest High school)
insert into User (id,name, school) values(47 ,Elroy, Elkhon South High)
insert into User (id,name, school) values(48 ,Rosemarie, Omaha North High School)
insert into User (id,name, school) values(49 ,Calaway, Millard Horizon High School)
insert into User (id,name, school) values(50 ,Guill, Hogwarts)
insert into User (id,name, school) values(51 ,Terry, Omaha South High School)
insert into User (id,name, school) values(52 ,Lucio, Wilson)
insert into User (id,name, school) values(53 ,Lenora, Parrish)
insert into User (id,name, school) values(54 ,Zelda, Millard Horizon High School)
insert into User (id,name, school) values(55 ,Regine, Wilson)
insert into User (id,name, school) values(56 ,Olin, Omaha Benson High school Magnet)
insert into User (id,name, school) values(57 ,Georgie, Omaha Northwest High school)
insert into User (id,name, school) values(58 ,Bryce, Omaha Benson High school Magnet)
insert into User (id,name, school) values(59 ,Federico, Hogwarts)

